# Dataset manifest for proximal/react-eval
# Add tasks using: harbor add <org>/<name>
# Publish using: harbor publish

[dataset]
name = "proximal/react-eval"
description = "Bonus 2 — 5 React+Vite tasks"
authors = []
keywords = []

[[tasks]]
name = "proximal/react-dravidian-studio-136645"
digest = "sha256:b694e8d22ee6e6353d0a31c841d41d9b2106d978e8c86424d739b17d8a77b48f"

[[tasks]]
name = "proximal/react-edo-japanese-restaurant-232594"
digest = "sha256:ab15f03337b185e417cd29b719b9627236fd13ec06b52aeb95df83e79221df18"

[[tasks]]
name = "proximal/react-high-gothic-museum-458726"
digest = "sha256:b3fbd9febeb3be13f3e370fee17a97ccc87e88ecfaeefa34370139893dee3a9f"

[[tasks]]
name = "proximal/react-persian-safavid-civic-173811"
digest = "sha256:31b5898213db627a06ec0b2c5f66bec7b6c0fd50b8be7c193fc2a4ed4b226f2e"

[[tasks]]
name = "proximal/react-roman-imperial-portfolio-560656"
digest = "sha256:267077cd9f1a020e0a2cccffef9e78b2f1cd9f117ec6c1c50b70fdb6e07b35ee"

